### ISSUE TITLE
Error when selection certain display currencies

### ISSUE THREAD

**Issue by simplyvinay** [simplyvinay/vue-expenses#4]
This seems to be an issue on linux machines as far as I can tell. The demo website is running linux on a docker container and when you select certain regions ( Angolan Kwanza for example ) you get a `The region name xx should not correspond to neutral culture; a specific culture name is required. (Parameter 'name')` . The same region when selected on a dev box running windows, doesn't throw any error

**Comment by Spawny17** [comment]
Is this still a bug? I've been unable to reproduce it.

**Comment by simplyvinay** [comment]
> Is this still a bug? I've been unable to reproduce it.

Thanks, I dont think it is, tried with a few currencies that was causing an error and it seems to work ok now. Will close the issue
