### ISSUE TITLE
Database import / export

### ISSUE THREAD

**Issue by elendil7** [simplyvinay/vue-expenses#55]
Is it currently possible to import / export the database, to back up my expenses?

If not, would it be a feature you'd consider implementing in the future?

Kind regards

**Comment by simplyvinay** [comment]
Hi @elendil7, database being used here is SQLite, which is file based, so you can backup `expenses.db` file from `vue-expenses-api/App_Data` folder..

**Comment by elendil7** [comment]
Thanks
